#!/usr/bin/env python3
"""Upsert a single 'Lua validation report' issue per repo from rdjson findings.

Used for master/push runs where there's no PR to comment on. Maintains ONE living issue
(deduped by the `wow-validator` label): updates its body with the current findings, or
closes it when master is clean. Never opens duplicates.

    python3 report_issue.py luacheck.rdjson luals.rdjson

Env: GITHUB_REPOSITORY (owner/repo), GH_TOKEN, optional RUN_URL.
"""
import collections
import json
import os
import subprocess
import sys
import tempfile

LABEL = "wow-validator"
TITLE = "🔍 Lua validation report (master)"
MARKER = "<!-- wow-validator -->"
REPO = os.environ.get("GITHUB_REPOSITORY", "")
RUN_URL = os.environ.get("RUN_URL", "")
CAP = 200  # max findings listed, to keep the issue body sane


def load(path):
    if not path or not os.path.exists(path) or os.path.getsize(path) == 0:
        return []
    d = json.load(open(path))
    tool = d.get("source", {}).get("name", "?")
    out = []
    for diag in d.get("diagnostics", []):
        loc = diag.get("location", {})
        start = loc.get("range", {}).get("start", {})
        msg = (diag.get("message") or "").splitlines()
        out.append({
            "tool": tool,
            "path": loc.get("path", "?"),
            "line": start.get("line", 0),
            "sev": diag.get("severity", "WARNING"),
            "code": (diag.get("code") or {}).get("value", ""),
            "msg": msg[0] if msg else "",
        })
    return out


def gh(*args):
    return subprocess.run(["gh", *args], capture_output=True, text=True)


def main():
    findings = load(sys.argv[1] if len(sys.argv) > 1 else None) \
        + load(sys.argv[2] if len(sys.argv) > 2 else None)

    # Dedup key: a label. Create it if missing (idempotent).
    gh("label", "create", LABEL, "--repo", REPO, "--color", "B60205",
       "--description", "Automated Lua validation findings", "--force")
    existing = gh("issue", "list", "--repo", REPO, "--label", LABEL, "--state", "open",
                  "--json", "number", "--jq", ".[0].number").stdout.strip()

    if not findings:
        if existing:
            gh("issue", "close", existing, "--repo", REPO,
               "--comment", "✅ master is clean — no luacheck/lua-language-server findings.")
            print(f"closed issue #{existing} (clean)")
        else:
            print("clean; no issue to manage")
        return

    by_tool = collections.Counter(f["tool"] for f in findings)
    by_sev = collections.Counter(f["sev"] for f in findings)
    errors = by_sev.get("ERROR", 0)
    L = [MARKER, "",
         f"**{len(findings)} findings** on `master` "
         f"({errors} error{'s' if errors != 1 else ''}, {by_sev.get('WARNING', 0)} warnings).",
         "", "| tool | findings |", "|---|---|"]
    for t, n in by_tool.most_common():
        L.append(f"| {t} | {n} |")
    L.append("")

    byfile = collections.defaultdict(list)
    for f in findings:
        byfile[f["path"]].append(f)
    shown = 0
    for path in sorted(byfile):
        L.append(f"<details><summary><code>{path}</code> ({len(byfile[path])})</summary>\n")
        for f in sorted(byfile[path], key=lambda x: x["line"]):
            if shown >= CAP:
                break
            icon = "🔴" if f["sev"] == "ERROR" else "🟡"
            code = f" `{f['code']}`" if f["code"] else ""
            L.append(f"- {icon} `{path}:{f['line']}`{code} {f['msg']}")
            shown += 1
        L.append("\n</details>")
        if shown >= CAP:
            L.append(f"\n_…capped at {CAP}; {len(findings) - CAP} more findings omitted._")
            break
    if RUN_URL:
        L.append(f"\n[CI run]({RUN_URL})")
    L.append("\n<sub>Auto-generated by wow-validator — updated each push to master, "
             "auto-closed when clean. Do not edit the title/label.</sub>")
    body = "\n".join(L)

    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as fh:
        fh.write(body)
        bp = fh.name

    if existing:
        gh("issue", "edit", existing, "--repo", REPO, "--body-file", bp)
        print(f"updated issue #{existing} ({len(findings)} findings)")
    else:
        r = gh("issue", "create", "--repo", REPO, "--title", TITLE,
               "--label", LABEL, "--body-file", bp)
        print(f"created issue: {r.stdout.strip() or r.stderr.strip()}")


if __name__ == "__main__":
    main()
